name: flutter_iot_cake_fast_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0<4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.1
  font_awesome_flutter: ^10.12.0
  url_launcher: ^6.3.2
  map_launcher: ^4.4.3
  carousel_slider: ^5.1.2
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/icon/cake.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
